### ISSUE TITLE
Improve the Readme section about building and running

### ISSUE THREAD

**Issue by jtanguy** [makers-for-life/makair-control-ui#14]
Based on the packaging work we are doing, we can improve the building instructions of the Readme on different systems.

As I am currently working on the packaging using archlinuxarm, I'll add the required packages to install to build and/or run

**Comment by dsferruzza** [comment]
This would definitely be useful, as well as defining the process to update/rebuild the image for the production line.

**Comment by valeriansaliou** [comment]
@jtanguy can you add instructions / docs on how to build the Linux distro image? I'll take over work on that one too as to make things lighter, more replicable and add a splash screen at boot if possible, w/ a MakAir logo.
