### ISSUE TITLE
add small icon if the soft is writing data on FS

### ISSUE THREAD

**Issue by waxzce** [makers-for-life/makair-control-ui#15]

**Comment by dsferruzza** [comment]
Maybe also the same when LoRa and Warp10 support is enabled?

**Comment by BlackYoup** [comment]
Yes, waxzce agrees but that can be done later

**Comment by BlackYoup** [comment]
Done in https://github.com/makers-for-life/makair-control-ui/commit/e3a6232f55e0ebc802e02ad9d14c537d8a742e1c (waiting for merge before closing this)

**Comment by jabby** [comment]
@BlackYoup can we create the corresponding PR in draft?

**Comment by BlackYoup** [comment]
@jabby unfortunately it got mixed up between the bigger ui and the expiratory trigger settings. It has been merged, see https://github.com/makers-for-life/makair-control-ui/pull/16
