### ISSUE TITLE
Conversion error when a button is pressed

### ISSUE THREAD

**Issue by Benhalor** [makers-for-life/makair-control-ui#25]
When any button is pressed (eg. Ppeak +), the value is displayed on the UI in mmH2O instead of cmH2O.

**Comment by Benhalor** [comment]
![Uploading image.png…]()

**Comment by Benhalor** [comment]
![image](https://user-images.githubusercontent.com/10956689/96334408-dfad7300-1070-11eb-89b1-19429abf40f4.png)

**Comment by atauveron** [comment]
Proposed fix in https://github.com/makers-for-life/makair-control-ui/pull/28

**Comment by atauveron** [comment]
Fix proposed in #28 does not fully solve the issue. Solving the issue may require modifying the data sent by the STM32 controller.

**Comment by valeriansaliou** [comment]
Can you describe the issue that's persisting?

**Comment by Benhalor** [comment]
This issue now appears to be fixed. Sorry
