### ISSUE TITLE
Manage alarm display

### ISSUE THREAD

**Issue by Benhalor** [makers-for-life/makair-control-ui#35]
When two alarms are raised on the same issue with different priority level, only display the higher priority alarm.

This concerns the following pairs: 
Patient is disconnected : Alarm 24 (medium) / Alarm 11 (high)
Plateau pressure is not reached : Alarm 22 (medium) / Alarm 12 (high)
PEEP pressure is not reached : Alarm 23 (medium) / Alarm 14 (high)
Battery LOW : Alarm 21 (medium) / Alarm 13 (high)

**Comment by valeriansaliou** [comment]
Done, patient unplugged alarm was the only one missing in the de-dup function.
