### ISSUE TITLE
No data is received when booting or not started

### ISSUE THREAD

**Issue by valeriansaliou** [makers-for-life/makair-control-ui#42]
Looks like the firmware is not sending the machine snapshot messages, or the telemetry library is ignoring them is state is not `running`.

**Comment by Benhalor** [comment]
You mean that the firmware should send a snapshot message at starting ?

**Comment by valeriansaliou** [comment]
Exactly. The UI does not receive any snapshot if it's not in running state. I've confirmed this does not come from the UI code.

**Comment by valeriansaliou** [comment]
After discussing this w/ @Benhalor ; we've concluded that we should add a new telemetry message type, which will hold all values for pressure, cycles, trigger and expiratory ratio.

This message type will be lightweight, and will be sent as an heartbeat (eg. every 500ms) to the UI whenever the current state is not `running`. This ensures a booting UI catches up with initial firmware data, and as well reacts to changes of values when in stopped mode.

Once the firmware is in running state, then those pressure (and others) values will be sent over the regular data snapshot message type, so the heartbeat message will not be sent anymore.

**Comment by valeriansaliou** [comment]
This has been addressed in c7d9a9090256967e67069d63644864afcf04664a
