### ISSUE TITLE
Change the I:E / Ti setting

### ISSUE THREAD

**Issue by Benhalor** [makers-for-life/makair-control-ui#52]
Currently, the I:E ratio is set, and the resulting Inspiratory Time (Ti) is displayed.
It would make more sense to do the opposite:
We would set the inspiratory time Ti, and display the resulting I:E ratio.

**Comment by valeriansaliou** [comment]
- mode pressure
  1. show measured + target (in ms; from insp. duration for target)
  2. show small measured i/e (from inverted existing formula)

- mode volume
  1. show measured (in ms; from insp. duration for target) 
  2. show small measured i/e (from inverted existing formula)

**Comment by valeriansaliou** [comment]
REQUIRES TELEMETRY PROTO UPDATE
