### ISSUE TITLE
Update the UI preview in README.md

### ISSUE THREAD

**Issue by dsferruzza** [makers-for-life/makair-control-ui#59]
This seems quite outdated:

![](https://raw.githubusercontent.com/makers-for-life/makair-control-ui/master/doc/screens/cycle-alarm.gif)

Maybe this could be the occasion to show the different modals/screens?

**Comment by valeriansaliou** [comment]
Yes, I wanted to do that, but I do not have any up to date recordings using the telemetry V2 protocol, as to show the UI in its real conditions.

Would you have any under hand? Could be a good idea to upload one V2 with proper respiratory data and some alarms sometimes, to the telemetry repo (and categorize each as V1 or V2).

**Comment by dsferruzza** [comment]
Indeed, I opened makers-for-life/makair-telemetry#25 to track this. I do not have a prototype so I cannot do it myself. Also protocol v2 still need some modifications so we shall wait a bit.

**Comment by valeriansaliou** [comment]
Done
