### ISSUE TITLE
Implement new error messages (watchdog, calibration failed, sensor failure, etc.)

### ISSUE THREAD

**Issue by valeriansaliou** [makers-for-life/makair-control-ui#80]
New telemetry errors should be added. Those errors should be shown using the error screen widget.

* Watchdog
* Calibration failed
* Sensor failure

**Comment by valeriansaliou** [comment]
Ping @dsferruzza (telemetry protocol + library update required).

**Comment by dsferruzza** [comment]
Do we need anything more than the error cause (enum)?

Maybe:
- calibration failed → the measured pressure
- sensor failed → the name of the sensor that failed

Also, do you think of more errors than the 3 you mentioned?

**Comment by valeriansaliou** [comment]
The watchdog could contain a reason enum, I don't really know the specifics of what needs to be raised there, but send me all the data you have on every error possible, that way I can be as specific as possible for the end-user / developer on the UI. That's also useful for manufacturing tests, eg. if a sensor is disconnected as to know which one.

**Comment by valeriansaliou** [comment]
Added UIs for those 3 new errors:

```rust
pub enum ChipError {
    // (...)
    Watchdog(String),
    SensorFailure(String),
    CalibrationFailure(String),
    // (...)
}
```

ENUM variants are not yet constructed, so this results in compilation warnings.

**Comment by valeriansaliou** [comment]
Done in b0f75a0c667ab234b86fa673ff4c26eaf6957642
